from call_minimax import *

if __name__ == '__main__':
    
    print("1")
    print(connect_four_mm(".......,.......,.......,.......,.......,.......", "red", 5))
    # print("2")
    # print(connect_four_mm(".......,.......,.......,.......,.......,.......", "red", 1))
    # print("3")
    # print(connect_four_mm(".......,.......,.......,.......,.......,.......", "red", 2))
    print("4")
    print(connect_four_mm(".......,.......,.......,.......,.......,.......", "red", 3))
    print("5")
    print(connect_four_mm(".......,.......,.......,.......,.......,.......", "red", 4))
    print("6")
    print(connect_four_mm(".......,.......,.......,.......,.......,.......", "red", 5))
    print("7")
    print(connect_four_mm("..y.r..,..y.r..,.......,.......,.......,.......", "red", 1))
    print("8")
    print(connect_four_mm("..y.r..,..y.r..,.......,.......,.......,.......", "yellow", 1))
    print("9")
    print(connect_four_mm("..y.r..,..y.r..,..y.r..,.......,.......,.......", "red", 1))
    print("10")
    print(connect_four_mm("..y.r..,..y.r..,..y.r..,.......,.......,.......", "red", 2))
    print("11")
    print(connect_four_mm("..y.r..,..y.r..,..y.r..,.......,.......,.......", "red", 3))
    # print("12")
    # print(connect_four_mm("r..y..r,r..y..r,......r,.......,.......,.......", "red", 1))
    # print("13")
    # print(connect_four_mm("r..y..r,r..y..r,......r,.......,.......,.......", "red", 2))
    # print("14")
    # print(connect_four_mm("r..y..r,r..y..r,......r,.......,.......,.......", "red", 3))
    # print("Done!")
